package com.lrisense.chatarchive;
import android.app.*;import android.os.*;import android.content.*;import android.webkit.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;import org.json.*;import java.util.*;
public class MainActivity extends Activity{
 WebView w;TextView s;boolean stop=false;int done,total;ArrayList<String> q=new ArrayList<>();
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);LinearLayout z=new LinearLayout(this);Button a=new Button(this),p=new Button(this),e=new Button(this);a.setText("COLETAR TUDO");p.setText("PAUSAR");e.setText("EXPORTAR JSON");z.addView(a,new LinearLayout.LayoutParams(0,-2,1));z.addView(p,new LinearLayout.LayoutParams(0,-2,1));z.addView(e,new LinearLayout.LayoutParams(0,-2,1));s=new TextView(this);s.setPadding(16,10,16,10);s.setText("Entre no ChatGPT e toque COLETAR TUDO.");r.addView(z);r.addView(s);w=new WebView(this);r.addView(w,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);WebSettings x=w.getSettings();x.setJavaScriptEnabled(true);x.setDomStorageEnabled(true);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(w,true);w.setWebChromeClient(new WebChromeClient());w.setWebViewClient(new WebViewClient());w.loadUrl("https://chatgpt.com/");a.setOnClickListener(v->discover());p.setOnClickListener(v->{stop=true;s.setText("Pausado.");});e.setOnClickListener(v->export());}
 String dec(String v)throws Exception{return v!=null&&v.startsWith("\"")?new JSONArray("["+v+"]").getString(0):v;}
 void discover(){stop=false;s.setText("Localizando conversas...");String j="(async()=>{let F=async u=>{let r=await fetch(u,{credentials:'include'});if(!r.ok)throw Error(r.status);return r.json()},o=[],S=new Set;for(let a of [false,true])for(let n=0;;){let d=await F('/backend-api/conversations?offset='+n+'&limit=100&order=updated&is_archived='+a),x=d.items||[];for(let c of x)if(c.id&&!S.has(c.id)){S.add(c.id);o.push(c.id)}if(x.length<100)break;n+=x.length}return JSON.stringify(o)})().then(x=>x).catch(e=>JSON.stringify({error:String(e)}))";w.evaluateJavascript(j,v->{try{String raw=dec(v);if(raw.startsWith("{")){s.setText("Não foi possível ler a sessão: "+raw);return;}JSONArray a=new JSONArray(raw);q.clear();for(int i=0;i<a.length();i++){String id=a.getString(i);if(!getPreferences(MODE_PRIVATE).contains("c_"+id))q.add(id);}total=q.size();done=0;s.setText("Encontradas "+a.length()+". Faltam "+total+".");next();}catch(Exception ex){s.setText("Erro: "+ex.getMessage());}});}
 void next(){if(stop)return;if(q.isEmpty()){s.setText("Concluído: "+count()+" conversas. Exporte o JSON.");return;}String id=q.remove(0);String j="(async()=>{let id='"+id+"',F=async u=>{let r=await fetch(u,{credentials:'include'});if(!r.ok)throw Error(r.status);return r.json()},d;try{d=await F('/backend-api/conversations/'+id+'?include_has_versions=true&num_turns=100')}catch(e){d=await F('/backend-api/conversation/'+id)}let m=[],N=x=>{if(!x)return;let p=x.content&&x.content.parts||[],t=Array.isArray(p)?p.filter(y=>typeof y==='string').join('\\n'):'';if(t.trim())m.push({role:x.author&&x.author.role||'unknown',text:t,create_time:x.create_time||null})};if(Array.isArray(d.messages))d.messages.forEach(N);else Object.values(d.mapping||{}).forEach(n=>N(n&&n.message));return JSON.stringify({id,title:d.title||'',url:'https://chatgpt.com/c/'+id,create_time:d.create_time||null,update_time:d.update_time||null,messages:m})})().then(x=>x).catch(e=>JSON.stringify({error:String(e)}))";w.evaluateJavascript(j,v->{try{String raw=dec(v);JSONObject o=new JSONObject(raw);if(!o.has("error"))getPreferences(MODE_PRIVATE).edit().putString("c_"+id,raw).apply();}catch(Exception ignored){}done++;s.setText("Coletadas "+done+" de "+total+"; armazenadas "+count());new Handler().postDelayed(this::next,200);});}
 int count(){int n=0;for(String k:getPreferences(MODE_PRIVATE).getAll().keySet())if(k.startsWith("c_"))n++;return n;}
 void export(){try{JSONArray a=new JSONArray();for(Object v:getPreferences(MODE_PRIVATE).getAll().values())if(v instanceof String)a.put(new JSONObject((String)v));JSONObject o=new JSONObject();o.put("total",a.length());o.put("conversations",a);File f=new File(getExternalFilesDir(null),"chatgpt-conversas.json");try(FileOutputStream z=new FileOutputStream(f)){z.write(o.toString(2).getBytes(StandardCharsets.UTF_8));}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"chatgpt-conversas.json");startActivityForResult(i,77);}catch(Exception ex){s.setText("Erro: "+ex.getMessage());}}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==77&&c==RESULT_OK&&d!=null)try{File f=new File(getExternalFilesDir(null),"chatgpt-conversas.json");try(InputStream in=new FileInputStream(f);OutputStream out=getContentResolver().openOutputStream(d.getData())){byte[] b=new byte[8192];for(int n;(n=in.read(b))>0;)out.write(b,0,n);}s.setText("JSON salvo.");}catch(Exception ex){s.setText("Erro ao salvar.");}}
 public void onBackPressed(){if(w.canGoBack())w.goBack();else super.onBackPressed();}
}