package com.thedoc.chatgptbackup;
public final class CollectorScript {
 private CollectorScript(){}
 public static final String CODE =
 "(async()=>{"+
 "window.__cgptStop=false;const S=m=>new Promise(r=>setTimeout(r,m));"+
 "async function F(u,n=0){let r=await fetch(u,{credentials:'include',cache:'no-store'});if((r.status==429||r.status>=500)&&n<6){await S(Math.min(1000*Math.pow(2,n),15000));return F(u,n+1)}if(!r.ok)throw Error(r.status+' '+u);return r.json()}"+
 "let ids=new Map();async function root(arch){let o=0,empty=0;while(!window.__cgptStop&&empty<2){let d=await F('/backend-api/conversations?offset='+o+'&limit=28&order=updated&is_archived='+arch);let a=d.items||[];if(!a.length){empty++;break}for(let x of a)ids.set(x.id,x);o+=a.length;if(a.length<28)break;await S(150)}}"+
 "async function projects(){let cur='';do{let u='/backend-api/gizmos/snorlax/sidebar?owned_only=true&conversations_per_gizmo=0'+(cur?'&cursor='+encodeURIComponent(cur):'');let d=await F(u);for(let z of(d.items||[])){let g=z.gizmo&&z.gizmo.gizmo||z.gizmo||{};let id=g.id;if(!id)continue;let pc='0';do{let q=await F('/backend-api/gizmos/'+id+'/conversations?cursor='+encodeURIComponent(pc));for(let x of(q.items||[])){x.project_id=id;x.project_name=g.display&&g.display.name||'';ids.set(x.id,x)}pc=q.cursor||'';await S(150)}while(pc&&!window.__cgptStop)}cur=d.cursor||''}while(cur&&!window.__cgptStop)}"+
 "function norm(m){if(!m)return null;let role=m.author&&m.author.role||m.role||'unknown',parts=m.content&&m.content.parts;let text=Array.isArray(parts)?parts.filter(x=>typeof x==='string').join('\\n'):(typeof m.content==='string'?m.content:(m.content&&m.content.text)||'');return text&&text.trim()?{role:role,text:text,create_time:m.create_time||null}:null}"+
 "async function full(id){try{let d=await F('/backend-api/conversations/'+id+'?include_has_versions=true&num_turns=100'),all=[];for(let m of(d.messages||[])){let x=norm(m);if(x)all.push(x)}let p=d.page_info||{};while(p.has_previous_page&&p.start_cursor&&!window.__cgptStop){d=await F('/backend-api/conversations/'+id+'?include_has_versions=true&num_turns=100&before='+encodeURIComponent(p.start_cursor));let old=[];for(let m of(d.messages||[])){let x=norm(m);if(x)old.push(x)}all=old.concat(all);p=d.page_info||{};await S(120)}d.__messages=all;return d}catch(e){let d=await F('/backend-api/conversation/'+id),all=[];for(let n of Object.values(d.mapping||{})){let x=norm(n&&n.message);if(x)all.push(x)}d.__messages=all;return d}}"+
 "try{await root(false);try{await root(true)}catch(e){BackupAndroid.error('archived-discovery',String(e))}try{await projects()}catch(e){BackupAndroid.error('projects-discovery',String(e))}let list=[...ids.values()],n=0;for(let x of list){if(window.__cgptStop)break;n++;if(BackupAndroid.has(x.id)){BackupAndroid.progress(n,list.length,'retomado');continue}try{let d=await full(x.id);BackupAndroid.save(JSON.stringify({id:x.id,title:d.title||x.title||'',url:'https://chatgpt.com/c/'+x.id,create_time:d.create_time||x.create_time||null,update_time:d.update_time||x.update_time||null,is_archived:d.is_archived??x.is_archived??false,project_id:x.project_id||d.gizmo_id||null,project_name:x.project_name||null,messages:d.__messages||[]}))}catch(e){BackupAndroid.error(x.id,String(e))}BackupAndroid.progress(n,list.length,'salvo');await S(180)}BackupAndroid.done(n)}catch(e){BackupAndroid.fatal(String(e))}})();";
}